# Generated by Django 4.1.6 on 2023-03-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "title",
                    models.TextField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "content",
                    models.TextField(default="", max_length=1000, verbose_name="内容"),
                ),
                ("publish_date", models.DateField(verbose_name="发布时间")),
            ],
        ),
    ]
